services:
  api:
    container_name: rag-api
    networks:
      - my_network
    build: ./backend
    ports:
      - "127.0.0.1:9898:8000"
    environment:
      DEBUG: "true"
      API_PROVIDER: "groq"
    depends_on:
      - searxng

  ui:
    container_name: rag-ui
    networks:
      - my_network
    build: ./ui
    ports:
      - "7860:7860"
    depends_on:
      - api

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "127.0.0.1:9998:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"


networks:
  my_network:
    driver: bridge
      #name: my_bridge_network
      #external: true
