name: Deploy to Kubernetes

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.VPS_USERNAME }}
          SERVER_IP: ${{ secrets.VPS_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          git remote set-url origin git@github.com:SZyablov/knowledge-flow.git && 
          git pull origin dev &&
          docker-compose up --build -d
          "

